DROP TABLE report1;
CREATE TABLE report1 AS SELECT TD.YEAR, TD.MONTH, AD.AIRPORT_CODE ,F.NOOFFLIGHTSARRIVALDELAYEDPERMONTHPERDESTINATIONAIRPORT NUM_OF_FLIGHTS_DEPARTURE_DELAYED 
FROM  AIRPORT_DIM AD, TIME_DIM TD,FACT_FLIGHTS F
WHERE AD.AIRPORT_KEY=F.FK2_AIRPORT_KEY AND TD.TIME_KEY = F.FK1_TIME_KEY;

DROP TABLE report2;
CREATE TABLE report2 AS SELECT TD.YEAR, TD.MONTH, AD.AIRPORT_CODE ,F.NOOFFLIGHTSWITHTAXIINTIMEDELAYEDPERMONTHPERDESTINATIONAIRPORT NUM_OF_FLIGHTS_TAXI_IN_TIME_DELAYED 
FROM  AIRPORT_DIM AD, TIME_DIM TD,FACT_FLIGHTS F
WHERE AD.AIRPORT_KEY=F.FK2_AIRPORT_KEY AND TD.TIME_KEY = F.FK1_TIME_KEY;
