Drop Table stagearea2 CASCADE CONSTRAINTS;

CREATE TABLE stagearea2 AS
SELECT PK, 
to_number(to_char(STAGEAREA1.FLIGHTDATE,'YYYY')) as The_year,
to_number(to_char(STAGEAREA1.FLIGHTDATE,'MM')) as The_month,
DESTAIRPORTCODE as AirportId,
DESTINTION_CITY AS DESTINTION_CITY,
DEPARTUREDELAY as departureDelayMin,
TAXIIN as taxiInTimeInMin FROM STAGEAREA1;
DROP TABLE tmp1_DD CASCADE CONSTRAINTS;
CREATE TABLE tmp1_DD AS SELECT THE_YEAR, THE_MONTH, AIRPORTID, COUNT(*) no_Of_Flights_DD FROM STAGEAREA2 where DEPARTUREDELAYMIN > 0 GROUP by THE_YEAR, THE_MONTH,  AIRPORTID
ORDER BY THE_YEAR, THE_MONTH,AIRPORTID;

DROP TABLE tmp1_TD CASCADE CONSTRAINTS;
CREATE TABLE tmp1_TD AS SELECT THE_YEAR, THE_MONTH, AIRPORTID, COUNT(*) no_Of_Flights_TD FROM STAGEAREA2 where TAXIINTIMEINMIN > 0 GROUP by THE_YEAR, THE_MONTH, AIRPORTID 
ORDER BY THE_YEAR, THE_MONTH, AIRPORTID;


-- TIME DIM
DROP TABLE tmp_time CASCADE CONSTRAINTS;
CREATE TABLE tmp_time (THE_YEAR,THE_MONTH) AS SELECT DISTINCT THE_YEAR, THE_MONTH FROM STAGEAREA2 ORDER BY THE_YEAR, THE_MONTH;

-- AIRPORT dimenSion;
DROP TABLE tmp_airport CASCADE CONSTRAINTS;
CREATE TABLE tmp_airport AS SELECT DISTINCT AIRPORTID, DESTINTION_CITY FROM STAGEAREA2;

-- Loading data into star schema
--Populating Time dimenion
insert into time_dim select timekey_Seq.nextval, the_year, the_month from tmp_time;

 --Populating Airport dimension
insert into airport_dim select airportkey_Seq.nextval, AIRPORTID , DESTINTION_CITY ,NULL, NULL from TMP_airport;

 --Populating Fact table
DROP TABLE TMP_FACT;
CREATE TABLE TMP_FACT AS SELECT tmp1_TD.THE_YEAR, tmp1_TD.THE_MONTH, tmp1_TD.AIRPORTID, tmp1_TD.NO_OF_FLIGHTS_TD, tmp1_DD.NO_OF_FLIGHTS_DD 
from tmp1_TD FULL OUTER JOIN tmp1_DD ON
tmp1_DD.THE_YEAR = tmp1_TD.THE_YEAR AND tmp1_DD.THE_MONTH = tmp1_TD.THE_MONTH AND tmp1_DD.AIRPORTID=tmp1_TD.AIRPORTID;

INSERT INTO FACT_flights (FACT_KEY, FK1_TIME_KEY, FK2_AIRPORT_KEY, NoOfFlightsDepDelayedPerMonthPerDestinationAirport, NOOFFLIGHTSWITHTAXIINTIMEDELAYEDPERMONTHPERDESTINATIONAIRPORT)
SELECT FACT_SEQ.nextval, TIME_DIM.TIME_KEY, Airport_DIM.AIRPORT_KEY, NO_OF_FLIGHTS_DD, NO_OF_FLIGHTS_TD FROM TIME_DIM, AIRPORT_DIM,TMP_FACT
WHERE TMP_FACT.THE_MONTH=TIME_DIM.MONTH AND TMP_FACT.THE_YEAR=TIME_DIM.YEAR AND AIRPORT_DIM.AIRPORT_CODE=TMP_FACT.AIRPORTID;

--SCD-3
UPDATE AIRPORT_DIM ad SET ad.CITY_NAME_NEW = 'NEW_NAME', ad.EFFECTIVE_DATE = sysdate WHERE ad.AIRPORT_CODE = 'CODE';
